name: Danger
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: danger/python@ddd0f980a4052618c49e242b7acfcebaf96ac889
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}